[package]
name = "coral"
version = "0.1.0"
authors = ["Aidan Heller <asfheller@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
topo = "0.13.0"
slotmap = "0.4.0"
anymap = "0.12.1"
downcast = "0.10.0"
